### ISSUE TITLE
How to use compileDynamicJump?

### ISSUE THREAD

**Issue by swazrgb** [ribrdb/desynced-tools#48]
I was wondering what the use case for compileDynamicJump is, and what typescript syntax to use to trigger it?

I managed to trigger it with:

```
    switch((state)) {
        case 0:
            notify("Hi");
            break;
    }
```

But I assume this isn't the intended syntax?

If #44 goes ahead I would like to rewrite it to support the following syntax:

```
switch(state) {
  case value("c_battery", 1):
    notify("First case");
    break;
}
```

and remove the generation of the setNumber instruction

**Comment by ribrdb** [comment]
Yes, I was intending this to support numeric switch statements. And it uses a random "id" part of the value so that you can have multiple switch statements.
If we have value literals it could make sense to support them in a switch statement, but that could be kind of tricky. What if you want to have multiple switch statements with the same value as a case? I guess maybe we couple put them into separate subroutines?

**Comment by swazrgb** [comment]
> What if you want to have multiple switch statements with the same value as a case

Good point. Better for users to use the label & jump instructions explicitly. Perhaps an inlined function (not a subroutine) could be the target of a jump. I'm looking for a clean syntax to implement a state machine pattern, and the numeric switch is good but I would prefer no additional instructions such as setNumber to be used.

![image](https://github.com/ribrdb/desynced-tools/assets/65694696/2c272181-e9b5-4d05-8009-e85a0c570d70)

**Comment by swazrgb** [comment]
What do you think about supporting this syntax?

```typescript
export function main(state: Value) {
    label(value("c_battery", 1), () => {
        notify("Setup phase");
    });

    label(value("c_battery", 2), () => {
        notify("Loop phase");
    });

    jump(state);
    state = value("c_battery", 1);
}
```

I believe this should be safe w.r.t. local variable scoping as long as `label` is only permitted in the top-most block, though it would complicate any future variable usage optimizations.

**Comment by ribrdb** [comment]
That seems like a good way to handle labels. I assume you meant to put the `jump` after setting `state`?

**Comment by swazrgb** [comment]
Yes, correct. I'll follow up with a PR later. Thanks!
