### ISSUE TITLE
negative coordinates

### ISSUE THREAD

**Issue by ttm02** [ribrdb/desynced-tools#58]
As far as I understand, the game does not support directly setting negative values.
Apart from coordinates, where I can add negative coordinates in game (in the add instruction).
Something like this does not compile:
```
let position = getLocation(self);
let new_pos = position + coord(-2, 0);
```
It is possible to work around this by using:
```
let position = getLocation(self);
let new_pos = position - coord(2, 0);
```
In terms of coordinates, I personally find this unintuitive (and therefore error-prone to use).

I don't know if fixing it is worthwhile, though. I just want to hint at this and think it may be a good idea to include it in documentation/examples.

**Comment by swazrgb** [comment]
Being able to use negative numbers (both for coordinates, and plain number types) is something I plan to PR.

Unrelated to desynced-tools, but based on what beathwho (developer of desynced) has said on discord the game might also allow setting negative values at some point via its UI.

**Comment by swazrgb** [comment]
This is now supported.
